### ISSUE TITLE
Compiles unchanged .html files

### ISSUE THREAD

**Issue by 3ilguun** [gulp-community/gulp-pug#116]
Is there any option? I have lots of templates. Everytime when i change my template compiles all files start to finish.

**Comment by jamen** [comment]
That is how gulp inherently works.  Each file is created into a vinyl, then passed down a stream to the plugin individually.  I think it would ultimately be more costly to check each time...  Even if not, don't think it is very applicable, since if you are running gulp you likely want things to build.

If you wanted to compile them more individually, you could setup different tasks for a different set of files, then wrap them together with something like: 

```
gulp.task('pug', ['pug:home', 'pug:contact', ..., 'pug:others'])
```

I also think this would be hard / confusing to develop.  You'd have to keep the cache somewhere to check the next time the process starts up.

There's my opinion.  :)

**Comment by 3ilguun** [comment]
`gulp-changed` worked for my problem. But thanks!

**Comment by joaocunha** [comment]
@53ck I've tried to use `gulp-changed` as well, but it didn't work for includes (it would have to compile the parent). Did you sort it somehow?

My build time is taking around 5 seconds and it's being a pain to iterate over the layout files.

**Comment by kyooriouskoala** [comment]
Experiencing same issue.  `gulp-changed` works fine but not working for includes. Tried `gulp-pug-inheritance` but it's not working either = /

Anyone with solution, please share. Thank you!

**Comment by joaocunha** [comment]
My performance issues were solved by using an express server to serve pug files instead of recompiling all of them at each save.
