### ISSUE TITLE
Dependency for pug 1.3.1 is impossible to meet

### ISSUE THREAD

**Issue by chippawah** [gulp-community/gulp-pug#128]
I don't know what happened but pug 1.3.1 isn't available from npm and gulp-pug throws a non zero exit code because of it.
<img width="962" alt="screen shot 2016-06-17 at 11 05 43 am" src="https://cloud.githubusercontent.com/assets/9676018/16157892/2ebb6e7e-3480-11e6-860b-179b4157ad6e.png">

**Comment by chippawah** [comment]
I avoided this by installing pug before gulp-pug. My docker build failed without that change. Perhaps the dependency be changed to ^1.3.1 as it appears to work in 2.0.0-beta3.

**Comment by jamen** [comment]
Are you installing `gulp-pug@latest`?  There are no peer dependencies in gulp-pug anymore, so you should not be getting any "UNMET" errors (though it harmless anyways?).  Also, `pug@1.3.1` doesn't exist, so I'm not sure where that is coming from.

Right now, there is [`pug@2.0.0-alpha6` in the dependencies](https://github.com/jamen/gulp-pug/blob/master/package.json#L16), but keep in mind you can [pass in your own pug instance](https://github.com/jamen/gulp-pug#pugopts) anyways.

I'm not updating the dependencies until they get an actual (non-prereleased) version out, because semver doesn't capture any of the prereleased versions unless you are specific about it (like we are now), and the only non-prereleased versions are marked as deprecated.  So, I am going to wait.

(Edit: Whoops, wrong button.)

**Comment by jamen** [comment]
Are you installing the latest version of gulp-pug?  There are no peer dependencies, so you shouldn't even be seeing that error.  pug@1.3.1

I'm going to refrain from
