### ISSUE TITLE
arguments whitout value

### ISSUE THREAD

**Issue by Groxot** [gulp-community/gulp-pug#129]
How i can write 
`<modal #modal>`
if write 
`modal(#modal)`
pug compile  
`<modal #modal="#modal">`

but on http://jade-lang.com/ its compile normal.

**Comment by jamen** [comment]
This is probably due to version differences.  `gulp-pug` right now uses [`pug@2.0.0-alpha6`](https://github.com/jamen/gulp-pug/blob/master/package.json#L16).  But, you can pass in your own `pug` instance of any version (see the docs in the README).

I will not be updating the version quite yet for [reasons stated in this issue](https://github.com/jamen/gulp-pug/issues/128#issuecomment-226833896).
