### ISSUE TITLE
Whitespace breaks mixins

### ISSUE THREAD

**Issue by ceremcem** [gulp-community/gulp-pug#131]
Following mixin does not work: 

```
mixin test(aaa)
    != '<script>'
    block <- there is a whitespace here
    != '</script>'
```

However following mixin works: 

```
mixin test(aaa)
    != '<script>'
    block<- there is no whitespace after `block`
    != '</script>'
```

**Comment by whaaaley** [comment]
`gulp-pug` is a wrapper around pug for use with gulp, not pug itself. I think you're looking for https://github.com/pugjs/pug

**Comment by jamen** [comment]
Note this could be due to version differences.  gulp-pug uses 2.0.0-alpha6.  Not updating until 2.0.0 is officially released, because all non-prereleased versions are deprecated right now.  Also note you can pass in your own pug instance with a custom version.

Otherwise if not fixed, it is an issue with pug.
