### ISSUE TITLE
Loop through an object with an array inside

### ISSUE THREAD

**Issue by sananes** [gulp-community/gulp-pug#161]
Hey guys!

So, I'm having a really hard time looping through an array inside an object.
```
- var packages = [
 {
   name: "Startup", price: 12.99, features: ['one, two']
 }, 
 {
   name: "Small Business", price: 49.99, features: ['one, two']
 },
 {
https://guides.github.com/features/mastering-markdown/
   name: "Corporate", price: 49.99, features: ['one, two']
 }, 
 {
   name: "Enterprise", price: 299.99, features: ['one, two']
 }
];
```
Here would be my pug file code:

```
    .container
      each package in packages
          p= package.name
          p= package.price
            ul
              each item in package.features
               li= item
```

Any reason why this wouldn't work?

**Comment by aderaaij** [comment]
Hey mate, fancy seeing you here! haha. There's no reason why that shouldn't work (see: https://codepen.io/aderaaij/pen/YrPejo). I think it's a syntax thing with the array in features. It goes `['one, two']` but I'm assuming this should be `['one', 'two']`.

**Comment by demurgos** [comment]
@Sananes 
Were you able to solve your issue? I believe that adernaaij was right: it's a simple syntax issue (single string with a comma instead of two strings separated by a comma).

I believe this issue is more related to the core [pug](https://github.com/pugjs/pug) syntax. If you still have a syntax issue, I recommend to submit a stack overflow question or open an issue on the main repo.

**Comment by phated** [comment]
I'm going to close this due to inactivity.
