### ISSUE TITLE
How to force compile template on change data?

### ISSUE THREAD

**Issue by verbart** [gulp-community/gulp-pug#174]
I use data from json files in templates. And I need a force restart Pug task on change it json. But Pug not compile because the template files did not change.

**Comment by staticfire** [comment]
Use 'gulp.watch' to watch you json file.

**Comment by verbart** [comment]
@ddawnbb Watch is not problem. Problem in force compile unchanged Pug files.

**Comment by jaireina** [comment]
@verbart could you put the code you used for your gulp build and the code in your pug files so we can understand your problem better and find a solution?

**Comment by verbart** [comment]
@jaireina https://github.com/verbart/verbart.github.io/blob/master/gulpfile.js#L89

**Comment by jaireina** [comment]
@verbart thanks for the link.

It seems like your issue is not related to pug, it is related to the require function of node that you're using and the fact that it caches all the requests done through it. Because of this cache, you never see your site updated.

You can circumvent this by using the fs module to read your JSON file instead of using require. I did a couple of tests and this worked:

`const fs = require('fs');`

In your views task, pass the parsed JSON file to your template through the works variable

`
.pipe(pug({
      data: {
        works: JSON.parse(fs.readFileSync('./src/data/works.json', 'utf8'))
      }
    }))
`

This issue can be closed.

**Comment by yocontra** [comment]
Yep, that ^

(Thanks @jaireina)
