### ISSUE TITLE
Where do the types/* dependencies belong?

### ISSUE THREAD

**Issue by phated** [gulp-community/gulp-pug#204]
I noticed that the dependencies for `@types/pug` are in `dependencies` but the `@types/node` are in the `devDependencies` - shouldn't these both be in the same place? Which one is correct?

cc @demurgos

**Comment by demurgos** [comment]
In the good old days before `@types/*`, it was simpler :smile:

Typescript supports two kinds of declarations: ambient (global) declarations and external module declarations. Global declarations are used to describe what's available in the environment (e.g. Node, Mocha tests, Electron). External declarations describe content you can require/import from other modules.

Before `@types/*`, type declarations were distributed with a tool called "typings". It knew about the difference between these two kinds of declarations and could ensure that you did not install multiple conflicting versions of the same global declaration.
With `@types/*`, type declarations became simple packages installed by `npm`. And `npm` does not handle global dependencies very well so there's a mismatch.

Since then, I am regularly asking this question myself and reevaluating the state of the ecosystem. Where do the `@types/*` dependencies belong?

I [posted the question and my conclusions](https://github.com/Microsoft/types-publisher/issues/81#issuecomment-459314973) in a discussion a few months ago. I hoped to get a reply from one of the maintainers there but did not have a reply yet. I'll try to reach to them again.

Here is my current position:
> My understanding is that type definitions declaring globals (e.g. `@types/node`, `@types/mocha`) should be treated as environment declarations, just like the `lib` field from `tsconfig.json`: `es5`, `dom`, `es2015.promise`, etc. This in turn means that they should only be defined by the top-level project.
Thus `@type/node` or any other global-inducing type definitions should be in `devDependencies` and never in `dependencies`. If a user wants to consume a lib depending on `@types/node`, he must explicitly provide it.
Since I started following this practice (for about 2 years now), I never had issues with duplicate global definitions again.

In the context of `gulp-pug`, `@types/node` is in the `devDependencies` because it defines globals (we could even drop it since we don't test the declarations, but it at least signals that Node definitions are needed). `@types/pug` is a regular dependency because it does not define globals and we use it to derive some of the types of `gulp-pug`.

**Comment by phated** [comment]
Couldn't they be in peerDependencies and devDeps?

**Comment by demurgos** [comment]
`@types/*` packages should have the same type as the corresponding implementation package. If `foo` is a `peerDependency` then `@types/foo` should be a peer dependency. If `bar` is a `dependency` then `@types/bar` should be a regular dependency. It helps ensuring that the declaration and implementation live at the same level in the dependency tree and are picked up properly.


`@types/node` is a special case because there's no corresponding package.

**Comment by demurgos** [comment]
By the way, `@types/*` is not only useful for Typescript users. It powers the VS Code's and Jetbrains autocompletion/quick doc/refactoring, so it's another reason why the dependency types should match. I wrote [a small post about it](https://demurgos.net/blog/2018/09/19/why-type-definitions/).

**Comment by phated** [comment]
@demurgos sounds good!  Thanks for the insight 😄
