### ISSUE TITLE
Please change the version of `jade` in `package.json` to allow larger ranges

### ISSUE THREAD

**Issue by ghost** [gulp-community/gulp-pug#23]
Like `1.x`, or `>=1`

As it is right now, it's meaninglessly locked to `>= 1.1, < 1.2` and jade is at `1.3.x`

**Comment by phated** [comment]
As you can see in #10 I don't trust the jade team to not break APIs and I believe in keeping the behavior of this module consistent between environments, so I will keep the `~`.

I will bump the version soon so you can have 1.3.  What features did they add?

**Comment by phated** [comment]
I'd also be willing to take a PR.

**Comment by ghost** [comment]
I'm curious -- Why do you think the external jade interface (`.compile` and `.render`) is going to change?  Other than the fact that the new project owner seems to be perfectly happy to "depreciate" features by just tossing them out the window in one day.  But he also seems to understand that it's only appropriate to do this on major version number changes.  At the rate he's incrementing the version number, it'll be at 2.0 next week anyway >_<

If internal features break, well I'd argue that it's really not the job of this library to police that.  As long as this passes to `jade.compile` correctly, and gets a value back (assuming jade doesn't throw compile errors), I think that's the only thing libraries like `gulp-jade` should be doing.

**Comment by phated** [comment]
It's not only about the `compile` and `compileClient` APIs used internally by this module, but also about the output produced by this module.  If I already have to maintain this package due to not-ideal interfaces provided by the `jade` package, I want to make sure the output of compilation stays as consistent as possible.  If I were to specify `^1.2`, something might change in the output in version `1.3` and then when deploying to production, things would change.  `peerDependencies` might help to solve this but they don't work great and typically cause me more problems than they are worth.

**Comment by phated** [comment]
Case in point, updating to 1.3.1 broke one of my tests.  I will be fixing it and publishing a new version soon.

**Comment by phated** [comment]
Fixed by https://github.com/phated/gulp-jade/commit/95147f49ae17ad9a355f3146609917be23c55c09 and published as 0.5.0
