### ISSUE TITLE
Bump jade version?

### ISSUE THREAD

**Issue by adam-lynch** [gulp-community/gulp-pug#39]
Can we bump up the jade version to the latest or is there a reason why you have `1.1 - 1.3`?

I want to be able to use `include:coffee(bare=true) x.coffee`.

**Comment by phated** [comment]
Some issues that may be of interest https://github.com/phated/gulp-jade/issues/23 and https://github.com/phated/gulp-jade/issues/36

**Comment by adam-lynch** [comment]
Thanks. I guess #23 covers this. Closing. P.S. Are you still using Jade yourself?

**Comment by phated** [comment]
Please update to `gulp-jade` version `0.7.0`

Version range bumped to `1.1 - 1.5`.  Yet another reason I hate to bump right after they bump (1.4.0) then 2 bug fix releases (1.4.1, 1.4.2) and another minor bump (1.5) in the span of 8 days.  Then, it will go stagnant for months.

I don't use Jade anymore because I think it is a poorly maintained project.

**Comment by adam-lynch** [comment]
@phated Ok, thanks! I can't seem to find something reliable & powerful enough but doesn't treat Windows users as second class.
