### ISSUE TITLE
pass locals in

### ISSUE THREAD

**Issue by edrex** [gulp-community/gulp-pug#9]
For HTML compilation it is useful to pass local variables into a Jade template. How should this be handled in gulp-jade?

**Comment by edrex** [comment]
Nevermind. I looked at the tests and found that I can pass in locals using the `data` key. Still, a docs issue.

**Comment by phated** [comment]
Should I add `locals` as an alias to `data`?

**Comment by diammondore** [comment]
can you share the example code how to use `locals` with data `key`?

**Comment by phated** [comment]
@diammondore I have no idea what you are talking about.

**Comment by diammondore** [comment]
sorry, my previous comment is not enough to describe my issues

@rayfranco thanks, your code works, but as global data, I need little different

i use template inheritance

`layout.jade` is primary, which contains header and footer

```
// layout.jade
doctype html
html
head
  ...
  title= pageTitle
  ...
body
  include ../partials/_header
  block content
  include ../partials/_footer
```

i am trying to pass page title using variable `pageTitle`

`index` and `inner` pages using same template (layout.jade) except page title and page content in main area

```
// index.jade
extends layout
pageTitle = "Frontpage title"
block content
  h1 frontpage content
```

```
// inner.jade
extends layout
pageTitle = "Inner page title"
block content
  h1 Inner page content
```

the issue is that the variable `pageTitle` is empty when jade compile the `index.html` and `inner.html`

I'm not good at coding, so often use examples from documentation
will be grateful for any advise
