### ISSUE TITLE
please update jade version in package.json 

### ISSUE THREAD

**Issue by zjuasmn** [gulp-community/gulp-pug#90]
Jade is 1.11.0 now. Please update jade version in package.json so that we could use new features in jade. Thank you for your awesome work!

**Comment by phated** [comment]
Please see https://github.com/phated/gulp-jade/pull/89 - we support custom jade versions through the `jade` option.  We typically don't bump jade for awhile because they often release bugs in newer versions and we wait for them to shake out.  Feel free to use the jade option and file tickets on the jade repo if you find any problems; the more people using it will find the bugs faster.  Thanks.
